version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cd website
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: website/public
  name: paketa-website-$(AWS_REGION)-$(date +%Y-%m-%d) 